parameters:
  - name: configuration
    type: string

steps:
  - template: checkout.yml

  - script: |
      sudo wget -qO /usr/local/bin/ninja.gz https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip
      sudo gunzip /usr/local/bin/ninja.gz
      sudo chmod a+x /usr/local/bin/ninja
    displayName: 'Install ninja'

  - task: CMake@1
    displayName: 'CMake LibSSL'
    inputs:
      workingDirectory: './Utilities/CMake/Linux/openssl/libssl'
      cmakeArgs: '-B ./../../../../../Build/libssl.Linux/build -D CMAKE_BUILD_TYPE=${{ parameters.configuration }} -G "Ninja"'

  - task: CMake@1
    displayName: 'CMake LibCrypto'
    inputs:
      workingDirectory: './Utilities/CMake/Linux/openssl/libcrypto'
      cmakeArgs: '-B ./../../../../../Build/libcrypto.Linux/build -D CMAKE_BUILD_TYPE=${{ parameters.configuration }} -G "Ninja"'

  - task: CMake@1
    displayName: 'CMake LibHttpClient'
    inputs:
      workingDirectory: './Utilities/CMake/Linux/libHttpClient'
      cmakeArgs: '-B ./../../../../Build/libHttpClient.Linux.C/build -D CMAKE_BUILD_TYPE=${{ parameters.configuration }} -G "Ninja"'

  - template: linux-build.yml