parameters:
  - name: platform
    type: string
  - name: configuration
    type: string

steps:
  - template: checkout.yml

  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 5.8'
    inputs:
      versionSpec: 5.8

  - task: NuGetAuthenticate@0

  - task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2
    displayName: NuGet restore
    inputs:
      restoreSolution: '*.sln'
    continueOnError: true

  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: 3.1.411
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # Build the Visual Studio 17 solution.
  # Ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/visual-studio-build
  - task: VSBuild@1
    displayName: Build ${{ parameters.platform }}+${{ parameters.configuration }} Solution
    inputs:
      solution: libHttpClient.vs2017.sln
      vsVersion: 15.0
      msbuildArchitecture: x64
      platform: ${{ parameters.platform }}
      configuration: ${{ parameters.configuration }}
      createLogFile: true
      logProjectEvents: true
      logFileVerbosity: 'diagnostic'

