parameters:
  - name: platform
    type: string
  - name: configuration
    type: string

steps:
  - checkout: self
    clean: true
    submodules: recursive

  - script: |
      git clean -ffdx
      git reset --hard HEAD
      git submodule foreach --recursive "git clean -ffdx"
      git submodule foreach --recursive "git reset --hard HEAD"
    displayName: Git clean after checkout

  - task: PkgESSetupBuild@12
    displayName: PkgES build setup
    inputs:
      useDfs: false
      productName: libHttpClient
      branchVersion: true
      extSync: true
      disableMsbuildVersion: true
